### ISSUE TITLE
Create Datascript learning material

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#11]
## Why?
There is a lot of excellent Clojure learning material out there already. We can curate that material. Less so for Datascript. We have a chance to make Learners' Datascript very relevant to Athens. Let's build this together 🏗️ 

## What and How?
Some or all (or more!) of the following: Curate existing Datascript learning material. Create Datascript koans. Improve the Datascript explorer. Create Datascript learning content (text, video, hybrid, interactive, etc)  

## Points to Ponder
1. How (and when!) can we use other people's resources in order to not do double-work? How should we give them credit?
2. Didn't Jeff already include some links on the onboarding doc?
3. How can we create Datascript koans in a way that also help Learners understand the Athens DB?
4. What are best practices when making koans?
5. How should we organize the koans?
6. What other types of learning material can we make?

## Action Items:
- [x] Create learning resource markdown page 
- [ ] Add links (and other info, like short summaries) to learning resources
- [x] Create Datascript koans doc
- [ ] Start and/or add list of koans
- [ ] Upgrade the Datascript explorer
- [ ] Create learning content (text, video, hybrid, interactive, etc)

**Comment by prabhath6** [comment]
I have found these learning resources helpful
1. [Datascript and Datomic: Data Modeling for Heroes](https://www.youtube.com/watch?v=tV4pHW_WOrY) - Mark Bastian
2. [How to Graph Your Data](https://www.youtube.com/watch?v=tbVwmFBnfo4) - Paula Gearon
3. [Learn Datalog Today](http://www.learndatalogtoday.org/)

**Comment by nthd3gr33** [comment]
Never saw the first one. Thanks for the share @prabhath6!
