### ISSUE TITLE
Yekrats Checkpoint Progress

### ISSUE THREAD

**Issue by Yekrats** [athensresearch/ClojureFam#15]
# Yekrats Checkpoint Progress

Real name: Scott Starkey
Github handle: @Yekrats
Discord handle: Yekrats#1938
Team Name: Team Abrotelia
Cohort: Quoll Cohort

**🏁 General Checkpoints 🏁**

- [x]  Introduce yourself to partner|team|cohort|mentor
- [x]  Choose an editor
- [x]  Get IDE and REPL working

**🏁 GitHub Checkpoints 🏁**

- [x]  Subscribe to Athens repo
- [x]  Subscribe to ClojureFam repo
- [x]  Scan of entire athens repo
- [ ]  Comment on existing issue
- [ ]  WIP Pull Request
- [ ]  Successful PR Merge 🚀

🏁 Getting Help 🏁

- [x]  Ask a question in Clojurians Slack
- [x]  Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [x]  Chapters 1-3
- [ ]  Chapters 4-6
- [ ]  Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [x]  20 problems
- [x]  40 problems
- [ ]  60 problems
- [ ]  80 problems
- [ ]  100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [x]  Chapters 3-4
- [x]  Chapters 5-6
- [x]  Chapters 7-8
- [x]  Chapters 9-11
- [x]  Chapters 12-13

**Comment by Yekrats** [comment]
Hey @nthd3gr33 - I do not believe I have the rights to add assignees or labels. (Maybe I have the rights but don't see how to do it?)

**Comment by Yekrats** [comment]
@nthd3gr33, @Bardia95, or @teodorlu - Please move my card from "Starting the Journey" to "In Route".

**Comment by nthd3gr33** [comment]
You are good to go @Yekrats! 🚀  Great job so far.

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
