### ISSUE TITLE
ghosttoaster|cimara Checkpoint Progress

### ISSUE THREAD

**Issue by gtoast** [athensresearch/ClojureFam#16]
## ghosttoaster|cimara Checkpoint Progress
Github handle: @gtoast
Discord handle (no @ please!): ghosttoaster|cimara
#4713
Team Name: Team Homer
Cohort: 2nd ClojureFam Cohort

🏁 **General Checkpoints** 🏁

* [x]  Introduce yourself to partner|team|cohort|mentor
* [x]  Choose an editor
* [x]  Get IDE and REPL working

🏁 **GitHub Checkpoints** 🏁

* [x]  Subscribe to Athens repo
* [x]  Subscribe to ClojureFam repo
* [ ]  Scan of entire athens repo
* [ ]  Comment on existing issue
* [ ]  WIP Pull Request
* [ ]  Successful PR Merge 🚀

🏁 **Getting Help** 🏁

* [x]  Ask a question in Clojurians Slack
* [ ]  Ask a question in Athens Discord

🏁 **Clojure from the Ground Up Checkpoints** 🏁

* [x]  Chapters 1-3
* [x]  Chapters 4-6
* [ ]  Chapters 7, 8, 10

🏁 **4Clojure Checkpoints** 🏁

* [x]  20 problems
* [x]  40 problems
* [x]  60 problems
* [ ]  80 problems
* [ ]  100 problems

🏁 **Clojure for the Brave and True Checkpoints** 🏁

* [ ]  Chapters 3-4
* [ ]  Chapters 5-6
* [ ]  Chapters 7-8
* [ ]  Chapters 9-11
* [ ]  Chapters 12-13

**Comment by gtoast** [comment]
@nthd3gr33 Move this card from "Starting the Journey" to "In Route" please! Thank you! Not sure how to add the learner label...

**Comment by nthd3gr33** [comment]
Great job @gtoast 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
