### ISSUE TITLE
pkiran6 Checkpoint Progress

### ISSUE THREAD

**Issue by prabhath6** [athensresearch/ClojureFam#17]
Real name: Prabhath Kiran
Github handle: @prabhath6
Discord handle: pkiran6#1730
Team Name: Team Euclid
Cohort: Quoll Cohort

🏁 General Checkpoints 🏁

- [x]  Introduce yourself to partner|team|cohort|mentor
- [x]  Choose an editor
- [x]  Get IDE and REPL working
- [x] [Set up](https://www.notion.so/prabhathkiran/Shadow-cljs-Intellij-project-980c475766804d71969e4c927cfa93ab) Intellij for Clojurescript development.

🏁 GitHub Checkpoints 🏁

- [x]  Subscribe to Athens repo
- [x]  Subscribe to ClojureFam repo
- [x]  Scan of entire athens repo
- [x]  Comment on existing issue
- [x]  WIP Pull Request
- [x]  Successful PR Merge 🚀

🏁 Getting Help 🏁

- [x]  Ask a question in Clojurians Slack
- [ ]  Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [x]  Chapters 1-3
- [ ]  Chapters 4-6
- [ ]  Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [x]  20 problems
- [x]  40 problems
- [x]  60 problems
- [ ]  80 problems
- [ ]  100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [ ]  Chapters 3-4
- [ ]  Chapters 5-6
- [ ]  Chapters 7-8
- [ ]  Chapters 9-11
- [ ]  Chapters 12-13

🏁 Build REST API in Clojure 🏁
- [x] [Rest API](https://www.notion.so/prabhathkiran/REST-API-2b307b83dfc24e719a4e8fd8c6a50655) with CRUD operations.

🏁 Build web app in Clojurescript 🏁
- [x] Build and [deploy](https://sad-mcclintock-de1196.netlify.app/) Clojurescript app to Netlify.

🏁 Datascript 🏁
- [x] Compelete all 8 chapters from [Learn Datalog Today](http://www.learndatalogtoday.org/)
- [x] Build a [simple application](https://www.notion.so/prabhathkiran/Build-a-simple-App-that-uses-Datascript-4df0f1bdc1ea4cdd94b205443c4657e2) with Datascript.

**Comment by nthd3gr33** [comment]
I love that you added more sections at the bottom. 🧠  Looking forward to see if you add more!

**Comment by nthd3gr33** [comment]
Great job @prabhath6 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
