### ISSUE TITLE
baibhavbista Checkpoint Progress

### ISSUE THREAD

**Issue by baibhavbista** [athensresearch/ClojureFam#18]
Github handle: @baibhavbista
Discord handle: baibhavbista#1537
Team Name: Team Zeno
Cohort: 3th ClojureFam Cohort

🏁 General Checkpoints 🏁

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁
- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [ ] Scan of entire athens repo
- [ ] Comment on existing issue
- [ ] WIP Pull Request
- [ ] Successful PR Merge 🚀

🏁 Getting Help 🏁
- [ ] Ask a question in Clojurians Slack
- [x] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁
- [x] Chapters 1-3
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁
- [x] 20 problems
- [x] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁
- [x] Chapters 3-4
- [x] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

**Comment by nthd3gr33** [comment]
Nice name change 😄

**Comment by nthd3gr33** [comment]
Great job @baibhavbista 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
