### ISSUE TITLE
Create a "Finding a Learner Partner" Board

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#19]
## Why?
To have a way for those who are waiting to get into either versions of the program to find a partner to study with until they enter the program. Partners could go on to be partners or group members when they enter the program.

## What and How?
The easiest way would be to use the two existing boards as a template to create the Learner Partner board. Each Learner could create an issue and then we place their cards into a "Searching for Partner" column. 

## Points to Ponder
1. How should we utilize columns here? Should we divide them by timezone? Or by level? Any other ideas?
2. Do issues just get closed once a Learner 
3. What information should be included on the README column?

## Action Items:
- [x] Create new project
- [x] Decide on general design and layout of board
- [x] Create README column
- [x] Create rest of columns
- [x] Create "In Search of Learner Partner" issue template

**Comment by mnihalm** [comment]
I think this is a great Idea!

To avoid horizontal bloat and potentially lose out on matches cause people may not scroll all the way to the right, I'm thinking if the columns are divided by Status, it would be easier to quickly scroll through and find potential partners.The Issue card can mention the timezone.

**Comment by nthd3gr33** [comment]
@mnihalm how do you propose breaking up Status? Besides "In search of partner" and "Found partner", what other columns can you think of?

> The Issue card can mention the timezone.
Great point 👍

**Comment by mnihalm** [comment]
hmm, The simplest way would probably be to do just that -

- Readme
- In search of partner
- Found Partner

Can't think of another column.

Cards can get deleted once someone is added to the cohort with a mentor. 
Thinking about what the cards can contain, This would be a good starting point -
- Name
- Timezone
- Prior Programming Experience


An alternative solution for the columns would be to have columns by Programming Experience? That would be like - "No Prior Experience" , "Beginner", "Intermediate", "Expert" Im not too sure about this :thinking:

**Comment by nthd3gr33** [comment]
Would you like to try to implement and make this @mnihalm?

Let me know, so I can give you the necessary write privileges.

**Comment by mnihalm** [comment]
Sure i can do it! :smile: 

Just to confirm, 
We create a project board with the columns mentioned and then start creating issues for all applicants who have not been added to an official cohort yet.

**Comment by nthd3gr33** [comment]
Just gave you write access @mnihalm. What about also adding one more column, so:

- Readme
- In Search of Learner Partner
- In Search of Learner Group
- Found Learner Partner/Group

In response to your request for confirmation:
> We create a project board with the columns mentioned  
Yes to this. 

> and then start creating issues for all applicants who have not been added to an official cohort yet  
Please make a single sample issue that the applicants can fill out themselves. If we have the resources (time), we can fill out those issues for them.

**Comment by mnihalm** [comment]
Hi @nthd3gr33 

Thanks, I've just created the board and the issue template. Do have a look and lemme know if anything needs to be changed/reworded. 

[Board](https://github.com/athensresearch/ClojureFam/projects/3)
[Issue template](https://github.com/athensresearch/ClojureFam/issues/31)

**Comment by nthd3gr33** [comment]
Awesome work @mnihalm 🙏

**Comment by nthd3gr33** [comment]
Made a few minor edits. Everything looks good. Will make an announcement about the new board right now.

Thanks so much for your efforts 🌿
