### ISSUE TITLE
Shafoo Checkpoint Progress

### ISSUE THREAD

**Issue by estellerostan** [athensresearch/ClojureFam#20]
### Shafoo Checkpoint Progress

Github handle: @estellerostan
Discord handle: shafoo#2019
Team Name: Team Aurelius
Cohort: 1st ClojureFam Cohort

:checkered_flag: **General Checkpoints** :checkered_flag:

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

:checkered_flag: **GitHub Checkpoints** :checkered_flag:

- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [ ] Scan of entire athens repo
- [x] Comment on existing issue
- [x] WIP Pull Request
- [x] Successful PR Merge :rocket:

:checkered_flag: **Getting Help** :checkered_flag:

- [ ] Ask a question in Clojurians Slack
- [ ] Ask a question in Athens Discord

:checkered_flag: **Clojure from the Ground Up Checkpoints** :checkered_flag:

- [x] Chapters 1-3
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

:checkered_flag: **4Clojure Checkpoints** :checkered_flag:

- [x] 20 problems
- [ ] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

:checkered_flag: **Clojure for the Brave and True Checkpoints** :checkered_flag:

- [x] Chapters 3-4
- [ ] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

:checkered_flag: **Rich Hickey Checkpoint** :checkered_flag:
- [x] Watch Ritch Hickey talks

**Comment by nthd3gr33** [comment]
> 🏁 Rich Hickey Checkpoint 🏁   

Should we break this category up into individual talks? 😆

**Comment by nthd3gr33** [comment]
Great job @estellerostan  🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
