### ISSUE TITLE
jewiet Checkpoint Progress

### ISSUE THREAD

**Issue by jewiet** [athensresearch/ClojureFam#22]
Github handle: @jewiet
Discord handle : jewiet#0699
Team Name: Aesara
Cohort: Partner

🏁 General Checkpoints 🏁

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x]  Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [ ] Subscribe to Athens repo
- [ ] Subscribe to ClojureFam repo
- [ ] Scan of entire athens repo
- [ ] Comment on existing issue
- [ ] WIP Pull Request
- [ ] Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ] Ask a question in Clojurians Slack
- [ ]  Ask a question in Athens Discord

🏁 Clojure for the Brave and True Checkpoints 🏁

- [x] Chapters 3-4
- [x] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

🏁 Learn Datascript  🏁
- [ ] Complete all chapters from [Learn datalog today](http://www.learndatalogtoday.org/)

🏁 Learn Re-frame  🏁
- [ ] Take an online [re-frame](https://purelyfunctional.tv/courses/understanding-re-frame/) course

🏁 Structure and Interpretation of Computer Programs
- [ ] Chapter 1 Building Abstractions with Procedures

**Comment by nthd3gr33** [comment]
Great job @jewiet 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
