### ISSUE TITLE
jorda0mega Checkpoint Progress

### ISSUE THREAD

**Issue by jorda0mega** [athensresearch/ClojureFam#26]
Github handle: @jorda0mega 
Discord handle (no @ please!): jorda0mega#0542
Team Name: Team Archimedes
Cohort: 2nd ClojureFam Cohort

🏁 General Checkpoints 🏁
- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁
- [x]  Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [x] Scan of entire athens repo
- [x] Comment on existing issue
- [x] WIP Pull Request
- [x] Successful PR Merge 🚀

🏁 Getting Help 🏁
- [x] Ask a question in Clojurians Slack
- [x] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁
- [ ] Chapters 1-3
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁
- [ ] 20 problems
- [ ] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [ ]  Chapters 3-4
- [ ]  Chapters 5-6
- [ ]  Chapters 7-8
- [ ]  Chapters 9-11
- [ ]  Chapters 12-13

**Comment by nthd3gr33** [comment]
Great job @jorda0mega 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'

**Comment by nthd3gr33** [comment]
Feel free to customize your progress card @jorda0mega 

I am assuming you don't plan to go back and read those books. Maybe you could add some Datalog | Datascript | reagent checkpoints instead. Then other Learners could look at your card to help customize their own.
