### ISSUE TITLE
alaq Checkpoint Progress

### ISSUE THREAD

**Issue by alaq** [athensresearch/ClojureFam#27]
Github handle: @alaq
Discord handle (no @ please!): alaq#6794
Team Name: Team Seneca
Cohort: 4th ClojureFam Cohort

🏁 General Checkpoints 🏁

- [X] Introduce yourself to partner|team|cohort|mentor
- [X] Choose an editor
- [X] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [X] Subscribe to Athens repo
- [X] Subscribe to ClojureFam repo
- [x] Scan of entire athens repo
- [x] Comment on existing issue
- [x] WIP Pull Request
- [x] Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ] Ask a question in Clojurians Slack
- [ ] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [X] Chapters 1-3
- [x] Chapters 4, 6
- [x] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [X] 20 problems
- [X] 40 problems
- [x] 60 problems
- [x] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [x] Chapters 3-4
- [x] Chapters 5-6
- [x] Chapters 7-8
- [x] Chapters 9-11
- [x] Chapters 12-13

🏁 Extra curricular resources 🏁
- [X] [Learn Datalog Today](http://www.learndatalogtoday.org/)
- [X] [Re-frame Tutorial with Code Examples](https://purelyfunctional.tv/guide/re-frame-building-blocks/)
- [x] re-frame documentation

**Comment by alaq** [comment]
@nthd3gr33 Could you please

- assign issue to me
- add the learner task
- add the issue to "ClojureFam Progress Board" Project
- move this card from "Starting the Journey" to "In Route"

**Comment by nthd3gr33** [comment]
Great job @alaq 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'

**Comment by alaq** [comment]
Log for July 8th:
- [X] Clojure for the Brave and True Chapter 6 (there was no exercises)
- [X] 4 4Clojure problems (now at 72 done!)
- [X] Started looking into our next issue https://github.com/athensresearch/athens/issues/126

Tweet: https://twitter.com/adrien/status/1281093498712834050
Daily post: https://github.com/alaq/learning-clojure-in-public/blob/master/posts/2020-07-08.md
