### ISSUE TITLE
Zeus Checkpoint Progress

### ISSUE THREAD

**Issue by itsrainingmani** [athensresearch/ClojureFam#28]
# Zeus Checkpoint Progress
Github handle: @itsrainingmani
Discord handle (no @ please!): Zeus#3345
Team Name: Team Seneca
Cohort: 4th ClojureFam Cohort

🏁 General Checkpoints 🏁

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [x] Scan of entire athens repo
- [x] Comment on existing issue
- [x] WIP Pull Request
- [x] Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ] Ask a question in Clojurians Slack
- [x] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [x] Chapters 1-3
- [x] Chapters 4-6
- [x] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [x] 20 problems
- [x] 40 problems
- [x] 60 problems
- [x] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [x] Chapters 3-4
- [x] Chapters 5-6
- [x] Chapters 7-8
- [x] Chapters 9-11
- [x] Chapters 12-13

🏁 Extra curricular resources 🏁

- [x] Learn Datalog Today
- [x] Re-frame Tutorial with Code Examples

**Comment by itsrainingmani** [comment]
@nthd3gr33, @Bardia95, or @teodorlu, would one of you please help me do the following:

```clojure
(do
     (assign issue to me)
     (add learner label)
     (add issue to "ClojureFam Progress Board" project)
     (move my card from "Starting the Journey" to "In Route"))
```

**Comment by nthd3gr33** [comment]
Great job @itsrainingmani 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'

And nice touch on your in-comment code 🧠

**Comment by itsrainingmani** [comment]
Thanks @nthd3gr33 !

**Comment by itsrainingmani** [comment]
Completed 40 4Clojure problems
