### ISSUE TITLE
Banditelol Checkpoint Progress

### ISSUE THREAD

**Issue by banditelol** [athensresearch/ClojureFam#29]
# Banditelol Checkpoint Progress

Github handle: @banditelol
Discord handle (no @ please!): banditelol#0582
Team Name: Team Seneca
Cohort: 4th ClojureFam Cohort

🏁 General Checkpoints 🏁

- [X]  Introduce yourself to partner|team|cohort|mentor
- [X]  Choose an editor
- [X]  Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [X]  Subscribe to Athens repo
- [X]  Subscribe to ClojureFam repo
- [ ]  Scan of entire athens repo
- [ ]  Comment on existing issue
- [ ]  WIP Pull Request
- [ ]  Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ]  Ask a question in Clojurians Slack
- [ ]  Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [ ]  Chapters 1-3
- [ ]  Chapters 4-6
- [ ]  Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [X]  20 problems
- [ ]  40 problems
- [ ]  60 problems
- [ ]  80 problems
- [ ]  100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [ ]  Chapters 3-4
- [ ]  Chapters 5-6
- [ ]  Chapters 7-8
- [ ]  Chapters 9-11
- [ ]  Chapters 12-13

**Comment by banditelol** [comment]
@nthd3gr33 can I get help to:

- assign issue to me
- add the learner task
- add the issue to "ClojureFam Progress Board" Project
- move this card from "Starting the Journey" to "In Route"

Thank You!

**Comment by nthd3gr33** [comment]
Great job @banditelol 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
