### ISSUE TITLE
Finding a Learning Group

### ISSUE THREAD

**Issue by mnihalm** [athensresearch/ClojureFam#31]
## "Your Name"

Github handle: @your_name
Discord handle: your_name#1234
Timezone: 
Prior Programming Experience: 
Hours per week: 
Short Description:

**Comment by jsjoeio** [comment]
Would it make sense to turn this into an actual [GitHub issue template](https://egghead.io./lessons/github-create-a-github-issue-template)?

**Comment by tangjeff0** [comment]
Done @jsjoeio https://github.com/athensresearch/ClojureFam/issues/new/choose
