### ISSUE TITLE
mnihalm Checkpoint Progress

### ISSUE THREAD

**Issue by mnihalm** [athensresearch/ClojureFam#37]
## 'mnihalm' Checkpoint Progress

Github handle: @mnihalm   
Discord handle :   Nihal#4648
Team Name: Team Aurelius  
Cohort: 5th ClojureFam Cohort

🏁 **General Checkpoints** 🏁
- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working 

🏁 **GitHub Checkpoints** 🏁
- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [ ] Scan of entire athens repo
- [ ] Comment on existing issue
- [ ] WIP Pull Request
- [ ] Successful PR Merge 🚀

🏁 **Getting Help** 🏁
- [ ] Ask a question in Clojurians Slack
- [ ] Ask a question in Athens Discord

🏁 **Clojure from the Ground Up Checkpoints** 🏁
- [ ] Chapters 1-3 
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

🏁 **4Clojure Checkpoints** 🏁
- [ ] 20 problems 
- [ ] 40 problems  
- [ ] 60 problems 
- [ ] 80 problems
- [ ] 100 problems

🏁 **Clojure for the Brave and True Checkpoints** 🏁
- [ ] Chapters 3-4
- [ ] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

**Comment by nthd3gr33** [comment]
Great job @mnihalm 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'

I also took the liberty of straightening up the formatting. Hope you don't mind 😄
