### ISSUE TITLE
(noor A F) Checkpoint progress

### ISSUE THREAD

**Issue by noorfathima11** [athensresearch/ClojureFam#38]
Github handle: @noorfathima11
Discord handle: (noor A F)#2379
Team Name: Team Aurelius
Cohort: 5th Cohort

🏁 General Checkpoints 🏁

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [x] Scan of entire athens repo
- [ ] Comment on existing issue
- [ ] WIP Pull Request
- [ ] Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ] Ask a question in Clojurians Slack
- [ ] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [ ] Chapters 1-3
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [ ] 20 problems
- [ ] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [ ] Chapters 3-4
- [ ] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

🏁 Datascript 🏁
- [ ] Complete all 8 chapters from Learn Datalog Today

🏁 Projects 🏁
- [ ] TBD

**Comment by noorfathima11** [comment]
@nthd3gr33 @Bardia95  @teodorlu can you assign me and add the card to "ClojureFam Progress Board" Project ? Thanks!

**Comment by nthd3gr33** [comment]
Great job @noorfathima11 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
