### ISSUE TITLE
jferreira Checkpoint Progress

### ISSUE THREAD

**Issue by JosePtm2** [athensresearch/ClojureFam#39]
Github handle: @JosePtm2
Discord handle (no @ please!): jferreira#1277
Team Name: Team Aurelius
Cohort: 5th ClojureFam Cohort

 Checkpoints 

- [x] Introduce yourself to partner|team|cohort|mentor

- [x] Choose an editor

- [x]  Get IDE and REPL working

GitHub Checkpoints 

- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo

- [ ] Scan of entire athens repo

- [ ] Comment on existing issue

- [ ] WIP Pull Request

- [ ] Successful PR Merge rocket

 Getting Help 

- [x] Ask a question in Clojurians Slack

- [ ] Ask a question in Athens Discord

 Clojure from the Ground Up Checkpoints 

- [ ] Chapters 1-3

- [ ] Chapters 4-6

- [ ]  Chapters 7, 8, 10

4Clojure Checkpoints

- [x] 20 problems

- [x] 40 problems

- [ ] 60 problems

- [ ] 80 problems

- [ ] 100 problems

Clojure for the Brave and True

- [x] Chapters 3-4

- [ ] Chapters 5-6

- [ ] Chapters 7-8

- [ ] Chapters 9-11

- [ ] Chapters 12-13

**Comment by JosePtm2** [comment]
@nthd3gr33, @Bardia95, @teodorlu
a. assign issue to me
b. add the learner task
c. add the issue to "ClojureFam Progress Board" Project
d. move this card from "Starting the Journey" to "In Route"

Tks :)

**Comment by nthd3gr33** [comment]
Great job @JosePtm2 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
