### ISSUE TITLE
Linguaphile Checkpoint Progress

### ISSUE THREAD

**Issue by amirsato** [athensresearch/ClojureFam#40]
Github handle: @amirsato
Discord handle: Linguaphile#5330
Team Name: Team Aurelius
Cohort: 5th Cohort

🏁 General Checkpoints 🏁

- [x] Introduce yourself to partner|team|cohort|mentor
- [x] Choose an editor
- [x] Get IDE and REPL working

🏁 GitHub Checkpoints 🏁

- [x] Subscribe to Athens repo
- [x] Subscribe to ClojureFam repo
- [ ] Scan of entire athens repo
- [x] Comment on existing issue
- [ ] WIP Pull Request
- [ ] Successful PR Merge 🚀

🏁 Getting Help 🏁

- [ ] Ask a question in Clojurians Slack
- [x] Ask a question in Athens Discord

🏁 Clojure from the Ground Up Checkpoints 🏁

- [ ] Chapters 1-3
- [ ] Chapters 4-6
- [ ] Chapters 7, 8, 10

🏁 4Clojure Checkpoints 🏁

- [x] 20 problems
- [ ] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

🏁 Clojure for the Brave and True Checkpoints 🏁

- [ ] Chapters 3-4
- [ ] Chapters 5-6
- [ ] Chapters 7-8
- [ ] Chapters 9-11
- [ ] Chapters 12-13

🏁 Projects 🏁

- [ ] TBD

**Comment by nthd3gr33** [comment]
Great job @amirsato 🚀 

- [x] Assigned the task to you
- [x] added the learner label
- [x] added issue to ClojureFam Progress Board Project
- [x] moved card to 'In Route'
