### ISSUE TITLE
Learner Progress Page

### ISSUE THREAD

**Issue by bonobo-d** [athensresearch/ClojureFam#41]
@nthd3gr33 
This is an update on the proposed Airtable+Form approach to tracking learners' progress.

In response to #8 Linguaphile created an Airtable base prototype to keep track of all the learners' progress. Later I created [this page](https://clojurefam-stats-page.netlify.app/) incorporating Airtable's information as tiles and graphs (just each cohort's average progress for now).

In this latest update, I have:
1. Added a form page for learners to submit their progress.
2. Restructured the Airtable schema and logic to be updatable with the form.
2. Made the chart load data dynamically (it was loaded at build time before!)

Note that Airtable's API is not great for security. To call it dynamically we basically have to send the API key with the website. For that reason, I have created a dedicated gmail and Airtable account and gave it read-only access to the base. Even if the API key is exposed it won't be able to write to Airtable. Still not pleasant but I guess it should be OK in this limited case.

**Remaining Questions**
- What do you think about the above flow and the security considerations?
- Where in the ClojureFam repo can I put the code? (Should I?)
- The free Airtable plan supports up to 1200 records. We would approach this limit if we have many form submissions from each learner for a few weeks. We can either pay for a higher plan, or find ways to limit how many submissions are necessary. What's you opinion here?

**Comment by tangjeff0** [comment]
Using project boards. Thanks for your work on this @bonobo-d @amirsato
