### ISSUE TITLE
Kevin

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/ClojureFam#47]

**Comment by doingandlearning** [comment]
Github handle: @doingandlearning

Discord handle (no @ please!): dolearning (Kevin)#3551

Twitter: @dolearning

Timezone: GMT

Prior Programming Experience:
Professional experience has been in PHP, Python and Javascript. Mostly working in React, Node and PHP at the moment. I use emacs so have some experience with elisp but mostly a Clojure/Lisp newb.

Short Description (Optional):
Hi 👋🏻 - I'm Kevin, an Irish man in England. I'm a full-stack web developer, an educator (formerly secondary Maths teaching, now egghead.io) and a learning addict. I'm very intested in PKM and use org-roam in Emacs at the moment but am fascinated by Athens. I have only just begun to dip my toe in the Clojure world and would be excited to explore more.
