### ISSUE TITLE
Migrate (and/or clone) docs from Notion to this repo

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#5]
Why?
Because we decided to have Github as our main source of truth for the ClojureFam program

What? 
Create clones of existing Notion docs

How? 

1. Go to Notion ClojureFam hub
2. Choose one or more docs to migrate to / clone on GitHub
3. Make a PR with the new doc(s)

Which docs?
- [x] Cohort Rosters https://www.notion.so/athensresearch/ClojureFam-Cohort-Rosters-37f3d96127474276b8c001a617ab9bd8
- [ ] Onboarding bardia to Education https://www.notion.so/athensresearch/Onboarding-bardia-to-Education-ClojureFam-1-1-Call-nthd3gr33-bardia-4a5a172dec644ba28ad4ae056ef11e4d

Bonus: Create a FAQs page similar to https://github.com/docker-library/official-images#more-faqs

**Comment by juniusfree** [comment]
@nthd3gr33 I'm working on the [Cohort Rosters](https://www.notion.so/athensresearch/ClojureFam-Cohort-Rosters-37f3d96127474276b8c001a617ab9bd8). In which folder should I put it? 😅

**Comment by nthd3gr33** [comment]
Closing after updating the Cohorts page.

Thanks for the help @juniusfree!
