### ISSUE TITLE
Joe Previte

### ISSUE THREAD

**Issue by jsjoeio** [athensresearch/ClojureFam#55]
**GitHub handle**: @jsjoeio 
**Discord handle**: jsjoeio#7954
**Timezone**: (Arizona/MST - no daylight savings)
**Prior Programming Experience**:
I learned how to code through freeCodeCamp. Since then, I've worked in the frontend doing JavaScript (React), fullstack doing React Native, GraphQL, TypeScript and Node. I've done some Python. Most recently I've been spending time learning Rust. As for functional programming, I understand some of the basic concepts.

**Short Description (Optional)**:
Hi, I'm Joe. I'm from Arizona and currently work for Facebook as an Open Source Developer Advocate. I focus on programming languages (Rust, Reason, and soon Hack). Outside of work, I help developers learn quickly. I'm really intrigued by this model y'all have and I'm eager to join and learn Clojure!

**Comment by itsrainingmani** [comment]
Welcome to ClojureFam Joe!

**Comment by jsjoeio** [comment]
HA! I was literally about to DM you on Twitter this! Thanks, Mani!

**Comment by alaq** [comment]
Good luck on your Clojure journey @jsjoeio!

**Comment by jsjoeio** [comment]
Thank you @alaq !
