### ISSUE TITLE
Makro

### ISSUE THREAD

**Issue by psmakro** [athensresearch/ClojureFam#67]
## Makro
Github handle: @psmakro
Discord handle: psmakro#7234
Timezone: GMT-4
Prior Programming Experience: I have programmed in a lot of languages of different paradigms at the university and at work but never became an real expert of any of them: C/C++, Java, PHP, Haskell, Prolog, Ruby, Python, JS, and even a tiny little bit of Common Lisp.
Short Description: I am very interested in learning Clojure because I like what I see in the language and the community. I have always wanted to contribute to an open source project. After finding references to Athens and reading more about the project and the ideas behind it, I am very excited to have the opportunity to learn with more people and at the same time contributing to it.

**Comment by tangjeff0** [comment]
Still interested in joining a cohort @psmakro?

**Comment by tangjeff0** [comment]
Awesome, please respond to the message in #school-builders of our Discord!
