### ISSUE TITLE
Update PM Board

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#7]
## Why?
Improve the contribution experience for School Builders (people that contribute to ClojureFam and Education)

## What and How?
Revamp our project board. You could use Jeff's board in Athens as inspiration (it is 🔥 after all). Or you can use a different style. That is up to you. 
Feel free to add more issues. Ask @teodorlu, @nthd3gr33, or @Bardia95 if you need some ideas.

## Action Items:
- [x] Choose a PM board style (consult examples and other resources)
- [x] Revamp the board
- [x] Add more issues

**Comment by teodorlu** [comment]
Good initiative. We need this sorely.

**Comment by teodorlu** [comment]
I took the liberty of turning your action items into checkboxes.

**Comment by juniusfree** [comment]
I added a README column to the kanban board just like in https://github.com/athensresearch/athens/projects/2

I also set the automation to the columns (e.g automatically add new issues to To Do column). You can check the settings on each column to see if that's appropriate

Other than that, I suggest we keep it simple for now. We can add more columns later if really needed.

**Comment by nthd3gr33** [comment]
Awesome @juniusfree 🚀  Thanks for setting up the automation. 

I like your idea of limiting the number of cards in the In Progress column. How many do you think we should limit to?

**Comment by nthd3gr33** [comment]
Also, we should think of what to add in the README column. 🤔  Maybe just a welcome card with a link to our Discord for now?

**Comment by juniusfree** [comment]
> I like your idea of limiting the number of cards in the In Progress column. How many do you think we should limit to?

My arbitrary suggestion is to limit to 5, and adjust as we get more experience working with this. More important is that we finish things and move things forward.

> Also, we should think of what to add in the README column. 🤔 Maybe just a welcome card with a link to our Discord for now?

I added several links to the README. Feel free to edit.

**Comment by nthd3gr33** [comment]
5 sounds like a perfect arbitrary number 😆 Can you set it to that please?

**Comment by nthd3gr33** [comment]
One side note: We are trying to capitalize Learners and Mentors out of respect. 🙏

**Comment by juniusfree** [comment]
> 5 sounds like a perfect arbitrary number 😆 Can you set it to that please?
🔮🧙‍♂️
I just realized that Github doesn't have this feature. 

Any issues that you want me to add @teodorlu @Bardia95 ? If none, I suggest we close issue. We can add new issues later. 👍👍

**Comment by nthd3gr33** [comment]
Added a couple new issues.

This issue is now closed. Great job @juniusfree 🚀
