### ISSUE TITLE
Sergio Santos

### ISSUE THREAD

**Issue by sergiotaerri** [athensresearch/ClojureFam#74]
## Sergio Santos

Github handle: @sergiotaerri
Discord handle: sergio#5539
Timezone: GMT-3
Prior Programming Experience: I'm a college student in Brazil, and while I have experience in my current internship at Software Engineering, most of my programming experience comes from personal and college projects I've coded in Java/Python/Clojure.
Short Description: As mentioned before, I'm a college student and have been studying Clojure for some months, mainly hopping through articles I find in the web in blogs such as practicalli. My main IT interests are functional programming, desktop Linux and open source, I look forward to learn more about this awesome ecosystem alongside my peers!

**Comment by vipermark7** [comment]
Hi @sergiotaerri ! I'm also interested in learning Clojure, though I was too busy to do so before. I know the basics already. 

My Discord name is spacey 🌌 #7238, I sent you a request already :)
