### ISSUE TITLE
Ar Nazeh

### ISSUE THREAD

**Issue by Nazeh** [athensresearch/ClojureFam#79]
## Ar Nazeh

Github handle: @Nazeh
Discord handle: Ar Nazeh#9494
Timezone: GMT +3
Prior Programming Experience: 1 year of JS, Ruby, and very little python.
Short Description: I am a software engineer working primarily on UI engineering and refactoring at Azavista.com. This is my first job in tech and I am excited to broaden my horizon and connect with engineers that I won't usually encounter elsewhere.

**Comment by vipermark7** [comment]
Hi @Nazeh  ! I'm also interested in learning Clojure, though I was too busy to do so before. I know the basics already.

My Discord name is spacey 🌌 #7238. I know the basics of Clojure so far

**Comment by Nazeh** [comment]
Hello @vipermark7, I too learned few stuff, mainly going through "Clojure from the ground up" chapters 1,2,3,4, and 6.
