### ISSUE TITLE
Create Team Progress Board

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#8]
## Why?
Improve the experience for Learners and Mentors in ClojureFam. Create a sense of:
1. progress as a team, and 
2. camaraderie as a cohort

## What and How?
Many different ways to implement this, but here is one example:
> Each card is a team, each column is a checkpoint. Checkpoints can be parts of the roadmap, such as 'first 20 4Clojure questions'

## Points to Ponder
1. Making a WIP PR (use `Draft`) and asking for comments is probably best for this type of task.
2. Teams will probably not move linearly from left to right in the kanban. For example, a Learner will not complete all 4Clojure problems before moving on to the Brave book.

## Action Items:
- [ ] Research progress boards that exist elsewhere
- [ ] Create a general design of this kanban board
- [ ] Create a list of checkpoints based on our existing roadmap
- [ ] Create first version of the progress board

**Comment by nthd3gr33** [comment]
@Linguaphile (Discord handle) made a great point in the #school-builders channel:

> People from the same team can do tasks at different speeds. I think it's more convenient to use a table.

So they created this: https://airtable.com/shrFCrWTTM5GdZrPV

**Comment by bonobo-d** [comment]
@languaphile @nthd3gr33 

Hi, I'm "Marco Μάρκος" on Discord 👋 

Here is [a simplified example](https://airtable.com/shryhi3klGz7liLrF) of the Airtable schema I suggested on Discord. (I'm jumping in quite out of the blue so please tell me if I'm missing the point!)

The schema has three tables:
1. A `Lessons` table, with the list of all exercises.
2. A `Learners` table, with all the members of all ClojureFam cohorts.
3. A `Cohorts` table with all the cohorts.

These tables have two-way links to each other. You can open/close the "Blocks" panel on the right to show the completion rates of all cohorts

I can send you an invite link to edit/play around with the base. Just PM or Discord me for that!

**Comment by amirsato** [comment]
Hi, I'm Linguaphile on Discord.

@bonobo-d thank you. You've made a good table.

What do you think, @nthd3gr33 ?

**Comment by amirsato** [comment]
@bonobo-d I've made changes to your table

1. Added rows with problems to the `Lessons` table (4Clojure, Brave Clojure, Clojure from the Ground Up)
2. Hid the 'Difficulty' field in the table `Lessons`
3. Hid the 'Curriculum' field in the table `Lessons`
4. Grouped the table `Lessons` by Difficulty
5. Changed the formulas 'Completion Rate' in the `Learners` table

**Comment by linguaphile** [comment]
To who it may concern: I am Linguaphile on Github. For some reason Iam
getting email apparently meant for Linguaphile on Discord. I assure you
that is some one else not jallison@williams.edu. Please adjust your email
emissions accordingly. Thanks Jim Allison

**Comment by tangjeff0** [comment]
Since you've already been tagged, the only way to stop getting email is to unsubscribe from the issue. Sorry for the mixup @linguaphile !

**Comment by tangjeff0** [comment]
Closing since I think we'll use Project Board for progress checking!
