### ISSUE TITLE
Create New Issue Template for Creating Issues

### ISSUE THREAD

**Issue by nthd3gr33** [athensresearch/ClojureFam#9]
## Why?
Improve the general PM workflow in our ClojureFam repo. 

## What and How?
Create a "New Issue Template" so that people can have an example to follow. You can either:
1. Use this issue and make a template from it, or
2. Search things like "Github issue templates" or "Github issue best practices" and create a template from it

## Points to Ponder
1. Do you need higher permissions to create a new issue template? 
2. Is it better to make one from scratch or copy an existing template from elsewhere?
3. How many templates do we need?

## Action Items:
- [ ] Decide on new issue template style(s)
- [ ] Create new issue template(s) (in markdown files if you don't have permissions)

**Comment by juniusfree** [comment]
This can be a good starting point https://github.com/stevemao/github-issue-templates/
